AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An application to scrape data from NFC-e.

Globals:
  Function:
    # There is something wrong with a higher timeout value.
    # It fails when deploying, showing the error message:
    # "invalid request provided: queue visibility timeout:
    # 30 seconds is less than function timeout: 100 seconds".
    # So, in order to fix this problem, I'm lowering the value
    # from 100 to 30.
    Timeout: 30
    LoggingConfig:
      LogFormat: JSON

Resources:
  ScrapperSNS:
    Type: AWS::SNS::Topic
    Properties:
      FifoTopic: true
      TopicName: "ScrapperSNS.fifo"

  ScrapperSQS:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: "ScrapperSQS.fifo"
      FifoQueue: true

  Subscriptions:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: arn:aws:sns:us-east-1:590183686355:ScrapperSNS.fifo
      Endpoint: !GetAtt ScrapperSQS.Arn

  ScrapperSQSQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref ScrapperSQS
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - sqs:SendMessage
            Resource: !GetAtt ScrapperSQS.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: arn:aws:sns:us-east-1:590183686355:ScrapperSNS.fifo

  ScrapperLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: app/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      FunctionName: ScrapperLambdaFunction
      Architectures:
        - x86_64
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ScrapperSQS.Arn
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: SaveDataSNS.fifo

Outputs:
  LambdaFunctionArn:
    Description: "ARN of the Lambda Function"
    Value: !GetAtt ScrapperLambdaFunction.Arn
